### ISSUE TITLE
Error: An unknown error occurred.

### ISSUE THREAD

**Issue by davidfekke** [Daplie/node-letsencrypt#15]
I received the following error when I tried to create a standalone cert using the following command:
```bash
sudo letsencrypt certonly --agree-tos --email david@fekke.com --standalone --domains fekke.com,www.fekke.com --config-dir ~/letsencrypt/etc --server https://acme-staging.api.letsencrypt.org/directory
```

Error: An unknown error occurred. My best guess is that we got an error that we're not used to from the ACME server and accidentally interpretted it as a success... or forgot to expose the error.
null
Error: Here's a stack trace, in case it helps:
    at /usr/local/lib/node_modules/letsencrypt-cli/bin/letsencrypt.js:121:15
    at /usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/index.js:307:13
    at /usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/index.js:202:26
    at tryCatcher (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:489:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:674:18)
    at Promise._fulfill (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:615:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:416:57)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:502:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:670:18)
    at Promise._reject (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:634:18)
    at Promise._rejectCallback (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:452:10)
Unhandled rejection Error: The CA was unable to validate the file you provisioned: undefined
    at handleErr (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/letiny-core/lib/get-certificate.js:350:17)
    at ensureValidation (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/letiny-core/lib/get-certificate.js:226:16)
    at Request._callback (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/letiny-core/lib/get-certificate.js:215:13)
    at Request.self.callback (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/request/request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/request/request.js:962:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

**Comment by coolaj86** [comment]
Sanity check: Were you...

* on a server with a public ip?
* allowing ports 443, 5001, and 80 through any firewalls?
* the domain in question pointed to the ip in question?

**Comment by rmhrisk** [comment]
Yes to all for me

**Comment by briggleman** [comment]
same issue.

- on server with public ip? yes
- allowing ports 443, 5001 and 80 through firewalls?  yes
- the domain in question pointed to the ip in question?  yes, can navigate to this domain using the domain name or address.

running: letsencrypt certonly --domains app.divvykid.com --email {removed} --agree-tos  --config-dir /etc/letsencrypt --webroot --webroot-path /app/public

**Comment by coolaj86** [comment]
Will either of you try with the latest version and see if this is still a problem?

**Comment by coolaj86** [comment]
Probably related fix: https://github.com/Daplie/letiny-core/pull/4

try v1.4.3

Closing, but please reopen if it's not fixed

**Comment by coolaj86** [comment]
Heads up, v2 is out: https://github.com/Daplie/node-letsencrypt

You can see the new API examples in the README and in the tests:
https://github.com/Daplie/node-letsencrypt/tree/master/tests
