### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by DylanPiercey** [Daplie/node-letsencrypt#17]
I am getting this:

```js
Unhandled rejection TypeError: Cannot read property 'indexOf' of undefined
    at /home/app/www/test-server/node_modules/pyconf/index.js:131:32
    at Array.forEach (native)
    at stringifyPythonConf (/home/app/www/test-server/node_modules/pyconf/index.js:109:20)
    at Object.writePythonConfFile [as writeFile] (/home/app/www/test-server/node_modules/pyconf/index.js:157:3)
    at Object.tryCatcher (/home/app/www/test-server/node_modules/bluebird/js/release/util.js:11:23)
    at Object.ret [as writeFileAsync] (eval at <anonymous> (/home/app/www/test-server/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at /home/app/www/test-server/node_modules/letsencrypt/lib/core.js:112:19
    at tryCatcher (/home/app/www/test-server/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/home/app/www/test-server/node_modules/bluebird/js/release/promise.js:491:31)
    at Promise._settlePromise (/home/app/www/test-server/node_modules/bluebird/js/release/promise.js:548:18)
    at Promise._settlePromise0 (/home/app/www/test-server/node_modules/bluebird/js/release/promise.js:593:10)
    at Promise._settlePromises (/home/app/www/test-server/node_modules/bluebird/js/release/promise.js:676:18)
    at Promise._fulfill (/home/app/www/test-server/node_modules/bluebird/js/release/promise.js:617:18)
    at /home/app/www/test-server/node_modules/bluebird/js/release/nodeback.js:42:21
    at /home/app/www/test-server/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:82:15)
```

It still created a valid cert however, looks like it's something to do with creating the renewal file but I am not sure.

**Comment by DylanPiercey** [comment]
The issue is here https://github.com/Daplie/node-letsencrypt/blob/master/lib/core.js#L112, writeing the renewal file fails.

**Comment by coolaj86** [comment]
I'm looking into this now to find the deeper issue.

Generally speaking you shouldn't be able to get to index 68 in an array of 65... y'know... so yeah... gonna figure that out...

**Comment by coolaj86** [comment]
Related issues:

* https://github.com/Daplie/letsencrypt-express/issues/11
* https://github.com/Daplie/letsencrypt-express/issues/14

**Comment by coolaj86** [comment]
Closing as this was fixed a few days ago. Reopen if it's still a problem for you.

**Comment by coolaj86** [comment]
Completely fixed in v2: https://github.com/Daplie/node-letsencrypt

You can see the new API examples in the README and in the tests:
https://github.com/Daplie/node-letsencrypt/tree/master/tests
