### ISSUE TITLE
TypeError on renewal: must start with number, buffer, array or string

### ISSUE THREAD

**Issue by coolaj86** [Daplie/node-letsencrypt#23]
From https://github.com/Daplie/letsencrypt-cli/issues/1

It looks like we've got a problem where we're expecting the private key to be loaded in a different format (or different property name) than when we save it.

The issue traces back to here:

<https://github.com/Daplie/node-letsencrypt/blob/master/lib/accounts.js#L109>

/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/lib/accounts.js

```
[Error]: letsencrypt-cli
TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:139:11)
    at new Buffer (buffer.js:58:10)
    at b64ToBinstr (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/letiny-core/lib/letsencrypt-forge-extra.js:16:10)
    at toForgePrivateKey (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/letiny-core/lib/letsencrypt-forge-extra.js:45:5)
    at Object.privateJwkToPems (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/letiny-core/lib/letsencrypt-forge-extra.js:91:12)
    at Object.tryCatcher (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/util.js:11:23)
    at Object.ret [as privateJwkToPemsAsync] (eval at <anonymous> (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at /usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/lib/accounts.js:109:21
    at tryCatcher (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:489:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:674:18)
    at Promise._fulfill (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:615:18)
    at PromiseArray._resolve (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letsencrypt/node_modules/bluebird/js/release/promise_array.js:143:14)
```

**Comment by ericfong** [comment]
have the same problem

**Comment by Dimtime** [comment]
"have the same problem"
"The workaround is to remove the renewals and accounts folders."
not cool at all)

**Comment by coolaj86** [comment]
Here's how to help out:

https://github.com/Daplie/letiny-core/issues/6

**Comment by coolaj86** [comment]
Fixed as of https://github.com/Daplie/node-letsencrypt/commit/c80f7aa624fdc6377feb60c419a7667a5a798caf

**Comment by coolaj86** [comment]
Completely fixed in v2: https://github.com/Daplie/node-letsencrypt

You can see the new API examples in the README and in the tests:
https://github.com/Daplie/node-letsencrypt/tree/master/tests
