### ISSUE TITLE
Node 6 support.

### ISSUE THREAD

**Issue by DylanPiercey** [Daplie/node-letsencrypt#25]
Currently in node 6 I am getting the following error:

```bash
[LE] register
[NLE]: begin registration
[LE DEBUG] reg domains [ 'b278df71.ngrok.io' ]
[LE] try email
[LE] arg.accountsDir success
[LE] use account
[DEBUG le/lib/core.js] registeryAsync err
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:287:9)
    at Function.Buffer.from (buffer.js:133:10)
    at new Buffer (buffer.js:112:17)
    at b64ToBinstr (./letiny-core/lib/letsencrypt-forge-extra.js:16:10)
    at toForgePrivateKey (./letiny-core/lib/letsencrypt-forge-extra.js:45:5)
    at Object.privateJwkToPems (./letiny-core/lib/letsencrypt-forge-extra.js:91:12)
    at Object.tryCatcher (./bluebird/js/release/util.js:16:23)
    at Object.ret [as privateJwkToPemsAsync] (eval at <anonymous> (./bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at ./letsencrypt/lib/accounts.js:109:21
    at tryCatcher (./bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (./bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (./bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (./bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (./bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (./bluebird/js/release/promise.js:628:18)
    at PromiseArray._resolve (./bluebird/js/release/promise_array.js:125:19)
```

Any ideas?

**Comment by coolaj86** [comment]
https://github.com/Daplie/node-letsencrypt/issues/23

I'll work on it soon (because I'm about to run into it myself). If you want to try your hand, it's just an object that's being passed in in the wrong format - like a forge object instead of an ursa object or instead of a string pem.

The workaround is to remove the `renewals` and `accounts` folders.

**Comment by coolaj86** [comment]
Here's how to help:

https://github.com/Daplie/letiny-core/issues/6

**Comment by coolaj86** [comment]
Completely fixed in v2: https://github.com/Daplie/node-letsencrypt

You can see the new API examples in the README and in the tests:
https://github.com/Daplie/node-letsencrypt/tree/master/tests
