### ISSUE TITLE
Generating new certificate does not work: Cannot read property 'expiresAt' of null

### ISSUE THREAD

**Issue by Rush** [Daplie/node-letsencrypt#36]
It just happened in testing of a deployment. 

```
Unhandled rejection TypeError: Cannot read property 'expiresAt' of null
at /myproject/node_modules/letsencrypt/lib/core.js:353:26
at tryCatcher (/myproject/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/myproject/node_modules/bluebird/js/release/promise.js:504:31)
at Promise._settlePromise (/myproject/node_modules/bluebird/js/release/promise.js:561:18)
at Promise._settlePromise0 (/myproject/node_modules/bluebird/js/release/promise.js:606:10)
at Promise._settlePromises (/myproject/node_modules/bluebird/js/release/promise.js:685:18)
at Promise._fulfill (/myproject/node_modules/bluebird/js/release/promise.js:630:18)
at Promise._resolveCallback (/myproject/node_modules/bluebird/js/release/promise.js:425:57)
at Promise._settlePromiseFromHandler (/myproject/node_modules/bluebird/js/release/promise.js:516:17)
at Promise._settlePromise (/myproject/node_modules/bluebird/js/release/promise.js:561:18)
at Promise._settlePromise0 (/myproject/node_modules/bluebird/js/release/promise.js:606:10)
at Promise._settlePromises (/myproject/node_modules/bluebird/js/release/promise.js:681:18)
at Async._drainQueue (/myproject/node_modules/bluebird/js/release/async.js:138:16)
at Async._drainQueues (/myproject/node_modules/bluebird/js/release/async.js:148:10)
at Immediate.Async.drainQueues [as _onImmediate] (/myproject/node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by Rush** [comment]
I don't wanna sound mean but were recent changes even tested?

After changing code to:
```
  return fetchFromConfigLiveDir(args).then(function (certs) {
    if (!certs || (Date.now() - certs.issuedAt) > (certs.expiresAt - certs.issuedAt) / 2) {
      // There is no cert available
      // Or the cert is more than half-expired
      return getCertificateAsync(args, defaults, handlers);
    }
```
then it works.

**Comment by coolaj86** [comment]
Fixed in v1.5.4. Sorry about that.

That was a change I was working on in v2.0.0 and accidentally merged too soon.

**Comment by coolaj86** [comment]
Version 2.x is now available: https://github.com/Daplie/node-letsencrypt

I did test it. https://github.com/Daplie/node-letsencrypt/tree/master/tests

**Comment by Rush** [comment]
@coolaj86 hehe, thanks man. Good job. I will test it soon as well. Will letsencrypt-express follow soon to use it?

**Comment by coolaj86** [comment]
Yes, it will. And I'm doing a master / worker example with cluster too (I've been needing that myself).

**Comment by Rush** [comment]
Ok. just make this optional please. :) Multiple master / worker uses across libraries is not very reliable.
