### ISSUE TITLE
Testing new letsencrypt in production turned out to be a disaster

### ISSUE THREAD

**Issue by Rush** [Daplie/node-letsencrypt#51]
Sorry for the dramatic title but it's how it went.

It seems there is no mechanism to handle concurrent requests for the same domain. Should it be handled by users of the library? If so, there is no indication of it in the README as it's advertised to just work. Anyway, node-letsencrypt quickly exhausts number of open files and requests .. and possibly DDos the ACME server: The below log is repeated thousands of times on my server.
```
Aug 28 08:21:13 dragon http-master[19616]: Unhandled rejection Error: connect EMFILE 104.108.34.195:443 - Local (undefined:undefined)
Aug 28 08:21:13 dragon http-master[19616]: at Object.exports._errnoException (util.js:870:11)
Aug 28 08:21:13 dragon http-master[19616]: at exports._exceptionWithHostPort (util.js:893:20)
Aug 28 08:21:13 dragon http-master[19616]: at connect (net.js:849:16)
Aug 28 08:21:13 dragon http-master[19616]: at net.js:984:7
Aug 28 08:21:13 dragon http-master[19616]: at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:64:16)
Aug 28 08:21:13 dragon http-master[19616]: at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:83:10)
Aug 28 08:21:13 dragon http-master[19616]: Unhandled rejection Error: connect EMFILE 104.108.34.195:443 - Local (undefined:undefined)
Aug 28 08:21:13 dragon http-master[19616]: at Object.exports._errnoException (util.js:870:11)
Aug 28 08:21:13 dragon http-master[19616]: at exports._exceptionWithHostPort (util.js:893:20)
Aug 28 08:21:13 dragon http-master[19616]: at connect (net.js:849:16)
Aug 28 08:21:13 dragon http-master[19616]: at net.js:984:7
Aug 28 08:21:13 dragon http-master[19616]: at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:64:16)
Aug 28 08:21:13 dragon http-master[19616]: at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:83:10)
Aug 28 08:21:13 dragon http-master[19616]: Unhandled rejection Error: EMFILE: too many open files, open '/etc/letsencrypt/accounts/acme-v01.api.letsencrypt.org/directory/89ec4b9e9ca1398524f01f6955f2e2c8/private_key.json'
Aug 28 08:21:13 dragon http-master[19616]: at Error (native)
Aug 28 08:21:13 dragon http-master[19616]: Unhandled rejection Error: EMFILE: too many open files, open '/etc/letsencrypt/accounts/acme-v01.api.letsencrypt.org/directory/1241bb4666f341cbd9bc343ac2bdc93d/private_key.json'
Aug 28 08:21:13 dragon http-master[19616]: at Error (native)
Aug 28 08:21:13 dragon http-master[19616]: Unhandled rejection Error: EMFILE: too many open files, open '/etc/letsencrypt/accounts/acme-v01.api.letsencrypt.org/
```

Lack of support for old letsencrypt directory structure will force every cert to renewed ... this may easily hit users with rate limits. 
```
Aug 28 08:21:12 dragon http-master[19616]: { type: 'urn:acme:error:rateLimited',
Aug 28 08:21:12 dragon http-master[19616]: detail: 'Error creating new cert :: Too many certificates already issued for exact set of domains: x.virtkick.com',
Aug 28 08:21:12 dragon http-master[19616]: status: 429 }
Aug 28 08:21:12 dragon http-master[19616]: TODO: modules which depend on this module should expose this error properly but since some of them don't, I expose it here directly:
Aug 28 08:21:12 dragon http-master[19616]: Error: [Error] letiny-core: not 200 ok
Aug 28 08:21:12 dragon http-master[19616]: at bodyToError (/usr/local/node/lib/node_modules/http-master/node_modules/letsencrypt/node_modules/le-acme-core/lib/get-certificate.js:55:15)
Aug 28 08:21:12 dragon http-master[19616]: at /usr/local/node/lib/node_modules/http-master/node_modules/letsencrypt/node_modules/le-acme-core/lib/get-certificate.js:246:20
Aug 28 08:21:12 dragon http-master[19616]: at Request._callback (/usr/local/node/lib/node_modules/http-master/node_modules/letsencrypt/node_modules/le-acme-core/lib/acme-client.js:113:7)
Aug 28 08:21:12 dragon http-master[19616]: at Request.self.callback (/usr/local/node/lib/node_modules/http-master/node_modules/letsencrypt/node_modules/le-acme-core/
```
When I moved my old `live` directory to the new `letsencrypt` directory it's getting errors like these (1000s of them):
```
Aug 28 08:20:49 dragon http-master[19616]: Unhandled rejection TypeError: base64 is not a function
Aug 28 08:20:49 dragon http-master[19616]: at Function.from (native)
Aug 28 08:20:49 dragon http-master[19616]: at Function.from (native)
Aug 28 08:20:49 dragon http-master[19616]: at Object.certInfo._pemToBinAb (/usr/local/node/lib/node_modules/http-master/node_modules/letsencrypt/node_modules/certpem/index.js:12:20)
Aug 28 08:20:49 dragon http-master[19616]: at Object.certInfo.debug.certInfo.getCertInfo (/usr/local/node/lib/node_modules/http-master/node_modules/letsencrypt/node_modules/certpem/index.js:19:27)
Aug 28 08:20:49 dragon http-master[19616]: at certInfo.info.certInfo.getBasicInfo (/usr/local/node/lib/node_modules/http-master/node_modules/letsencrypt/node_modules/certpem/index.js:42:20)
Aug 28 08:20:49 dragon http-master[19616]: at Object.module.exports.attachCertInfo (/usr/local/node/lib/node_modules/http-master/node_modules/letsencrypt/lib/utils.js:13:18)
Aug 28 08:20:49 dragon http-master[19616]: at /usr/local/node/lib/node_modules/http-master/node_modules/letsencrypt/lib/core.js:337:26
Aug 28 08:20:49 dragon http-master[19616]: at tryCatcher (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/util.js:16:23)
Aug 28 08:20:49 dragon http-master[19616]: at Promise._settlePromiseFromHandler (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/promise.js:509:31)
Aug 28 08:20:49 dragon http-master[19616]: at Promise._settlePromise (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/promise.js:566:18)
Aug 28 08:20:49 dragon http-master[19616]: at Promise._settlePromise0 (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/promise.js:611:10)
Aug 28 08:20:49 dragon http-master[19616]: at Promise._settlePromises (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/promise.js:690:18)
Aug 28 08:20:49 dragon http-master[19616]: at Promise._fulfill (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/promise.js:635:18)
Aug 28 08:20:49 dragon http-master[19616]: at Promise._resolveCallback (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/promise.js:430:57)
Aug 28 08:20:49 dragon http-master[19616]: at Promise._settlePromiseFromHandler (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/promise.js:521:17)
Aug 28 08:20:49 dragon http-master[19616]: at Promise._settlePromise (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/promise.js:566:18)
```

```
Aug 28 08:19:18 dragon http-master[19616]: ERROR in le-sni-auto:
Aug 28 08:19:18 dragon http-master[19616]: ERROR in le-sni-auto:
Aug 28 08:19:18 dragon http-master[19616]: TimeoutError: operation timed out
Aug 28 08:19:18 dragon http-master[19616]: at afterTimeout (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/timers.js:46:19)
Aug 28 08:19:18 dragon http-master[19616]: at [object Object].timeoutTimeout [as _onTimeout] (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/timers.js:76:13)
Aug 28 08:19:18 dragon http-master[19616]: at Timer.listOnTimeout (timers.js:92:15)
Aug 28 08:19:18 dragon http-master[19616]: TimeoutError: operation timed out
Aug 28 08:19:18 dragon http-master[19616]: at afterTimeout (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/timers.js:46:19)
Aug 28 08:19:18 dragon http-master[19616]: at [object Object].timeoutTimeout [as _onTimeout] (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/timers.js:76:13)
Aug 28 08:19:18 dragon http-master[19616]: at Timer.listOnTimeout (timers.js:92:15)
Aug 28 08:19:18 dragon http-master[19616]: ERROR in le-sni-auto:
Aug 28 08:19:18 dragon http-master[19616]: TimeoutError: operation timed out
Aug 28 08:19:18 dragon http-master[19616]: at afterTimeout (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/timers.js:46:19)
Aug 28 08:19:18 dragon http-master[19616]: at [object Object].timeoutTimeout [as _onTimeout] (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/timers.js:76:13)
Aug 28 08:19:18 dragon http-master[19616]: at Timer.listOnTimeout (timers.js:92:15)
Aug 28 08:19:18 dragon http-master[19616]: ERROR in le-sni-auto:
Aug 28 08:19:18 dragon http-master[19616]: TimeoutError: operation timed out
Aug 28 08:19:18 dragon http-master[19616]: at afterTimeout (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/timers.js:46:19)
Aug 28 08:19:18 dragon http-master[19616]: at [object Object].timeoutTimeout [as _onTimeout] (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/timers.js:76:13)
Aug 28 08:19:18 dragon http-master[19616]: at Timer.listOnTimeout (timers.js:92:15)
Aug 28 08:19:18 dragon http-master[19616]: ERROR in le-sni-auto:
Aug 28 08:19:18 dragon http-master[19616]: TimeoutError: operation timed out
Aug 28 08:19:18 dragon http-master[19616]: at afterTimeout (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/timers.js:46:19)
Aug 28 08:19:18 dragon http-master[19616]: at [object Object].timeoutTimeout [as _onTimeout] (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/timers.js:76:13)
Aug 28 08:19:18 dragon http-master[19616]: at Timer.listOnTimeout (timers.js:92:15)
Aug 28 08:19:18 dragon http-master[19616]: ERROR in le-sni-auto:
Aug 28 08:19:18 dragon http-master[19616]: TimeoutError: operation timed out
Aug 28 08:19:18 dragon http-master[19616]: at afterTimeout (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/timers.js:46:19)
Aug 28 08:19:18 dragon http-master[19616]: at [object Object].timeoutTimeout [as _onTimeout] (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/timers.js:76:13)
Aug 28 08:19:18 dragon http-master[19616]: at Timer.listOnTimeout (timers.js:92:15)
Aug 28 08:19:18 dragon http-master[19616]: ERROR in le-sni-auto:
Aug 28 08:19:18 dragon http-master[19616]: TimeoutError: operation timed out
Aug 28 08:19:18 dragon http-master[19616]: at afterTimeout (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/timers.js:46:19)
Aug 28 08:19:18 dragon http-master[19616]: at [object Object].timeoutTimeout [as _onTimeout] (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/timers.js:76:13)
Aug 28 08:19:18 dragon http-master[19616]: at Timer.listOnTimeout (timers.js:92:15)
Aug 28 08:19:18 dragon http-master[19616]: ERROR in le-sni-auto:
Aug 28 08:19:18 dragon http-master[19616]: TimeoutError: operation timed out
Aug 28 08:19:18 dragon http-master[19616]: at afterTimeout (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/timers.js:46:19)
Aug 28 08:19:18 dragon http-master[19616]: at [object Object].timeoutTimeout [as _onTimeout] (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/timers.js:76:13)
Aug 28 08:19:18 dragon http-master[19616]: at Timer.listOnTimeout (timers.js:92:15)
Aug 28 08:19:18 dragon http-master[19616]: ERROR in le-sni-auto:
Aug 28 08:19:18 dragon http-master[19616]: TimeoutError: operation timed out
Aug 28 08:19:18 dragon http-master[19616]: at afterTimeout (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/timers.js:46:19)
Aug 28 08:19:18 dragon http-master[19616]: at [object Object].timeoutTimeout [as _onTimeout] (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/timers.js:76:13)
Aug 28 08:19:18 dragon http-master[19616]: at Timer.listOnTimeout (timers.js:92:15)
Aug 28 08:19:18 dragon http-master[19616]: ERROR in le-sni-auto:
Aug 28 08:19:18 dragon http-master[19616]: TimeoutError: operation timed out
Aug 28 08:19:18 dragon http-master[19616]: at afterTimeout (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/timers.js:46:19)
Aug 28 08:19:18 dragon http-master[19616]: at [object Object].timeoutTimeout [as _onTimeout] (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/timers.js:76:13)
Aug 28 08:19:18 dragon http-master[19616]: at Timer.listOnTimeout (timers.js:92:15)
Aug 28 08:19:18 dragon http-master[19616]: ERROR in le-sni-auto:
Aug 28 08:19:18 dragon http-master[19616]: ERROR in le-sni-auto:
Aug 28 08:19:18 dragon http-master[19616]: TimeoutError: operation timed out
Aug 28 08:19:18 dragon http-master[19616]: at afterTimeout (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/timers.js:46:19)
Aug 28 08:19:18 dragon http-master[19616]: at [object Object].timeoutTimeout [as _onTimeout] (/usr/local/node/lib/node_modules/http-master/node_modules/bluebird/js/release/timers.js:76:13)
```

Should I be implementing my own rate limitting on top of node-letsencrypt? My idea is to keep a promise cache per domain so that only one cert at a time is being retrieved.

The code being run is this:
https://github.com/virtkick/http-master/blob/master/modules/letsencrypt.js

For now I had to revert to older http-master on the production servers which runs previous node-letsencrypt.

**Comment by Rush** [comment]
Solution I'm gonna be soon testing:
```
  let getCertificatesAsync = require('memoizee')(lex.getCertificatesAsync, {
    maxAge: 5000,
  });
```

**Comment by Rush** [comment]
Another small issue. When testing and creating an account from scratch I'm getting some garbage in the logs:
```
[pyconf] WARN index past array length:
68 68 undefined
unexpected duplicate key 'keyPath': '/home/rush/letsencrypt/live/test.rushbase.net/privkey.pem'
unexpected duplicate key 'checkpoints': '0'
unexpected duplicate key 'account': '499ca499d3140e35cebaf737a044ce48'
```

**Comment by Rush** [comment]
Unfortunately I'm still getting tons of timesouts from auto-sni :-(

**Comment by coolaj86** [comment]
You've got a number of issues here and I don't know the answer to all of them. Let me see what I can come up with:

Error: EMFILE: too many open files
---

I think this is an issue with `ulimit` in the linux operating system. Some hosting providers artificially lower the `ulimit` so that they can oversell their systems.

```
sudo ulimit -n

sudo ulimit -n 4096
```

See <http://stackoverflow.com/questions/21515463/how-to-increase-maximum-file-open-limit-ulimit-in-ubuntu>

base64 is not a function
-----------

Node introduced a breaking change in `Buffer` and `ArrayBuffer` between 4.x and 6.x and due to a bug in some (or all) versions of 4.x less than v4.5, there's no way to properly detect and polyfill (that I could find). Prior to some version of 4.x the shim works. After 4.5 a bugfix was backported.

I had gone through and hard-coded a shim in a few places, but apparently there's still a place where it must be finding the < 4.5 bug.

same-request caching
---------

This needs to be looked at. I had started on this, but I may not have finished it. I like your intermediate solution and if that works well for you I might just include it in core.

Old Directory Structure Unsupported
--------------------------

Well, technically, it is supported and only the default locations have changed. All of the filenames and relative paths are the same.

WARN index past array length
---------------

The good news is that those config files are only for compatibility with the python client and they're not important for `node-letsencrypt` moving forward.

The bad news is that those errors started after I moved all of that code out to its own plugin and since I don't think anyone actually cares about compatibility with the python client, I'm not going to waste my time trying to fix it.

The `le-storage-certbot` plugin simply needs to be replaced. It's not a good optional for production even if it were fixed. It "works", so I use it, but the long term plan is to replace it with something that is cluster safe and uses a database rather than relying on config files on the file system.

Rate Limits
-------------

The letsencrypt servers define the rate limits and I can't do anything about that.

* each email has one or more accounts
* each account has one or more domains
* each ip may register x accounts in y days
* each ip may register x domains in y days

The only solution I can think of is either to create a database-based plugin and have a script to migrate the `certbot`-style structure into the database or to give `le-storage-certbot` some love.

You're absolutely right that blowing away the entire directory structure and starting over from scratch is going to cause issues for large hosts.

**Comment by coolaj86** [comment]
I think the best solution that addresses the greatest number of concerns is to work on https://github.com/Daplie/node-letsencrypt/issues/39 and implement it in such a way that it can use either email address or account id so that you can easily import all of you existing certificates.

Can we set aside some time to help each other with that?

**Comment by Rush** [comment]
I will be able to put aside some time later this week. (I hope!) Thanks for changing the title to something appropriate.

> I think this is an issue with ulimit in the linux operating system. Some hosting providers artificially lower the ulimit so that they can oversell their systems.

Nah, the limits are high enough. The problem was rather caused by the number of simultaneous requests that node-letsencrypt was doing due to my web server being bashed by impatient people trying to view their favorite website. :) That website gets on average 500 people who are constantly logged in. (through a websocket connection)

> Node introduced a breaking change in Buffer and ArrayBuffer between 4.x and 6.x and due to a bug in some (or all) versions of 4.x less than v4.5,

Ah apparently I need an upgrade than, thanks!

> The le-storage-certbot plugin simply needs to be replaced. It's not a good optional for production even if it were fixed.

As a temporary solution can the python compatibility be simply disabled?

> each email has one or more accounts
> each account has one or more domains
> each ip may register x accounts in y days
> each ip may register x domains in y days
> each domain may have x subdomains

Maybe this is the reason why the memoized version did not work for me... maybe my host has crossed the limits during my initial test. Do you know the specific limits about numbers of accounts, domains per ip per days?

Thanks, I really appreciate your help!

**Comment by coolaj86** [comment]
Disable certbot compat: no, we just need to create a different plugin. I could make modifications to use json rather than the python config, but then it would be a json plugin and it would still have filesystem race conditions and potential for corruption. We need a better solution that is thread- / cluster-safe and has indexes.

Rate limits: <https://letsencrypt.org/docs/rate-limits/>

You are welcome. I'll continue to help as best as I can.

**Comment by Rush** [comment]
Unfortunately I cannot get a certificate generated. Node 6.6.0. Ideas?
```
Sep 20 23:51:50 dragon node[24771]: Unhandled rejection TypeError: Cannot read property '_getEncoder' of undefined
Sep 20 23:51:50 dragon node[24771]: at DERNode.use [as _use] (/usr/local/node/lib/node_modules/http-master/node_modules/asn1.js/lib/asn1/encoders/der.js:244:16)
Sep 20 23:51:50 dragon node[24771]: at DERNode._getUse (/usr/local/node/lib/node_modules/http-master/node_modules/asn1.js/lib/asn1/base/node.js:431:27)
Sep 20 23:51:50 dragon node[24771]: at DERNode.encode [as _encodeValue] (/usr/local/node/lib/node_modules/http-master/node_modules/asn1.js/lib/asn1/base/node.js:560:21)
Sep 20 23:51:50 dragon node[24771]: at DERNode.encode [as _encode] (/usr/local/node/lib/node_modules/http-master/node_modules/asn1.js/lib/asn1/base/node.js:482:21)
Sep 20 23:51:50 dragon node[24771]: at DERNode.<anonymous> (/usr/local/node/lib/node_modules/http-master/node_modules/asn1.js/lib/asn1/base/node.js:535:23)
Sep 20 23:51:50 dragon node[24771]: at Array.map (native)
Sep 20 23:51:50 dragon node[24771]: at DERNode.encode [as _encodeValue] (/usr/local/node/lib/node_modules/http-master/node_modules/asn1.js/lib/asn1/base/node.js:524:30)
Sep 20 23:51:50 dragon node[24771]: at DERNode.encode [as _encode] (/usr/local/node/lib/node_modules/http-master/node_modules/asn1.js/lib/asn1/base/node.js:482:21)
Sep 20 23:51:50 dragon node[24771]: at DERNode.encode [as _encodeValue] (/usr/local/node/lib/node_modules/http-master/node_modules/asn1.js/lib/asn1/base/node.js:560:48)
Sep 20 23:51:50 dragon node[24771]: at DERNode.encode [as _encode] (/usr/local/node/lib/node_modules/http-master/node_modules/asn1.js/lib/asn1/base/node.js:482:21)
Sep 20 23:51:50 dragon node[24771]: at DERNode.<anonymous> (/usr/local/node/lib/node_modules/http-master/node_modules/asn1.js/lib/asn1/base/node.js:535:23)
Sep 20 23:51:50 dragon node[24771]: at Array.map (native)
Sep 20 23:51:50 dragon node[24771]: at DERNode.encode [as _encodeValue] (/usr/local/node/lib/node_modules/http-master/node_modules/asn1.js/lib/asn1/base/node.js:524:30)
Sep 20 23:51:50 dragon node[24771]: at DERNode.encode [as _encode] (/usr/local/node/lib/node_modules/http-master/node_modules/asn1.js/lib/asn1/base/node.js:482:21)
Sep 20 23:51:50 dragon node[24771]: at DERNode.encode [as _encodeValue] (/usr/local/node/lib/node_modules/http-master/node_modules/asn1.js/lib/asn1/base/node.js:497:30)
Sep 20 23:51:50 dragon node[24771]: at DERNode.encode [as _encode] (/usr/local/node/lib/node_modules/http-master/node_modules/asn1.js/lib/asn1/base/node.js:482:21)
```

**Comment by wmertens** [comment]
I am encountering the duplicate key errors as well, but I don't really know how to address those. I set up LE v2 according to the docs, using all the default handlers.

**Comment by insightfuls** [comment]
The duplicate key errors you can ignore. They are harmless.

**Comment by coolaj86** [comment]
High rate limits and wildcard support is now available in Let's Encrypt v2.

greenlock.js v2.2.0+ has ACME v2 support.

Official repo at https://git.coolaj86.com/coolaj86/greenlock.js
